#variable list
DNA = "GCTGAGACTTCCTGGACGGGGGACAGGCTGTGGGGTTTCTCAGATAACTGGGCCCCTGCGCTCAGGAGGCCTTCACCCTCTGCTCTGGGTAAAGTTCATTGGAACAGAAAGAAATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTGAT"
x = len(DNA)
block_size = 10
blocking = 10
z = 0
print (x)
my_list = []
#loops
while z < x :
   my_list.append(DNA[z:blocking]) 
   z += block_size
   blocking += block_size

split_dna = ""
for _ in my_list:
   split_dna += (" " + (_) + " ") 
#printing
formatted_dna = split_dna.strip()
print(formatted_dna)
