#Given a string and two integers, return two slices of the string between the positions represented by the two numbers pairs
Word = "TheUniversityOfManchesterFacultyofBiologyMedicineAndHealth"
print(Word[3:13]+" "+Word[15:25])

#Challenge
DNA = "GCTGAGACTTCCTGGACGGGGGACAGGCTGTGGGGTTTCTCAGATAACTGGGCCCCTGCGCTCAGGAGGCCTTCACCCTCTGCTCTGGGTAAAGTTCATTGGAACAGAAAGAAATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTGAT"
print(DNA[137:143] + " " + DNA[274:280] )
#Answer is GAAGAA GAAGAA