#variable list
dna = "GCTGAGACTTCCTGGACGGGGGACAGGCTGTGGGGTTTCTCAGATAACTGGGCCCCTGCGCTCAGGAGGCCTTCACCCTCTGCTCTGGGTAAAGTTCATTGGAACAGAAAGAAATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGGAGCCTACAAGAAAGTACGAGATTTAGTCAACTTGTTGAAGAGCTATTGAAAATCATTTGTGCTTTTCAGCTTGACACAGGTTTGGAGTATGCAAACAGCTATAATTTTGCAAAAAAGGAAAATAACTCTCCTGAACATCTAAAAGATGAAGTTTCTATCATCCAAAGTATGGGCTACAGAAACCGTGCCAAAAGACTTCTACAGAGTGAACCCGAAAATCCTTCCTTGCAGGAAACCAGTCTCAGTGTCCAACTCTCTAACCTTGGAACTGTGAGAACTCTGAGGACAAAGCAGCGGATACAACCTCAAAAGACGTCTGTCTACATTGAATTGGGATCTGATTCTTCTGAAGATACCGTTAATAAGGCAACTTATTGCAGTGTGGGAGATCAAG"
dna_length = len(dna)
block_size = 10
blocking = 10
start = 0
dna_list = []


#loops and functions
def new_line():
   if start%60 == 0 and start < dna_length:
      dna_list.append("\n" + str(start + 1))

while start < dna_length :
   if start == 0:
      dna_list.insert (0, str(1))
   dna_list.append(dna[start:blocking]) 
   start += block_size
   blocking += block_size
   new_line()

split_dna = ""
for _ in dna_list:
   if start == 0 or start%60 == 0:
      split_dna += ((_) + " ") 
   else:
      split_dna += (" " + (_) + " ") 




#printing
formatted_dna = split_dna.strip()
print(formatted_dna.lower())


